Fix missing require for clojure.test
The error will not show itself if clojure.test has been loaded by some
other code.  But in those cases where clojure.test is not used elsewhere
slack-rtm/core fails to load with error:

IllegalStateException: Attempting to call unbound fn: #'clojure.test/function?